@startuml
left to right direction
skinparam packageStyle rectangle

actor Користувач as usr
rectangle Застосунок {
    usr -- (Змоделювати ДТП)
    (Змоделювати ДТП) <.. (Ввести дані): <<include>>
    
    (Ввести дані) <.. (Ввести параметри учасників руху): <<include>>
    (Ввести дані) <.. (Ввести параметри сценарію): <<include>>
    (Змоделювати ДТП) <.. (Створити звіт): <<include>>
    (Ввести параметри сценарію) <.. (Ввести погоду): <<include>>
    (Ввести параметри сценарію) <.. (Ввести тип перехрестя): <<include>>

    (Ввести параметри сценарію) <.. (Ввести кількість учасників): <<include>>
    
    (Ввести параметри учасників руху) <.. (Внести параметри нового учасника): <<include>>
    (Ввести параметри учасників руху) <.. (Внести параметри першого учасника): <<include>>
    (Внести параметри першого учасника) .> (Внести параметри нового учасника) : <<extends>>
    (Внести параметри нового учасника) <.. (Ввести масу): <<include>>
    (Внести параметри нового учасника) <.. (Ввести початкову швидкість): <<include>>
    (Внести параметри нового учасника) <.. (Ввести тип авто): <<include>>
    (Внести параметри нового учасника) <.. (Ввести розміри авто): <<include>>
    (Внести параметри нового учасника) <.. (Ввести прискорення гальмування): <<include>>

    (Змоделювати ДТП) <.. (Обробити дані): <<include>>
    
    (Змоделювати ДТП) <.. (Зчитати введені дані): <<include>>
    (Змоделювати ДТП) <.. (Програти сценарій): <<include>>
    ' (Зчитати введені дані) .> (Ввести параметри сценарію) : <<include>>
    ' (Зчитати введені дані) .> (Ввести параметри учасників руху) : <<include>>

    (Зчитати введені дані) <..(Ввести вектор руху учасників): <<include>>

    
    (Зчитати введені дані) <.. (Ініціалізувати учасників): <<include>>

    (Зчитати введені дані) <.. (Ініціалізувати середовище): <<include>>




}

@enduml
